# Generated by Django 5.0.6 on 2024-05-15 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_desription_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='live',
            field=models.BooleanField(default=True),
        ),
    ]
